### ISSUE TITLE
Update of invalid tasks

### ISSUE THREAD

**Issue by rtkg** [neckutrek/hiqp#11]
void Task::update(RobotStatePtr robot_state) does not enforce that the task jacobian, task function value and or the task signs are valid. 

    void Task::update(RobotStatePtr robot_state)
      {
        if (!def_ || !dyn_) return;
        if (def_->update(robot_state) != 0) return;
        dyn_->update(robot_state, def_->e_, def_->J_);
      }

This can observably lead to crashes in the solver when, e.g, the dimensions of the Jacobian don't match the task signs as these invalid tasks are appended unchecked in TaskManager::getVelocityControls(.)

*Proposed Solution*

  * check for failure in Task::update(.) and return an error code to be used in order to avoid appending invalid tasks in TaskManager::getVelocityControls(.).

**Comment by neckutrek** [comment]
A set of size assertions in Task::update() would (or should) at all times never fail. If they would fail, the user would want to fix the bug, recompile and re-run the control program. I therefore deem such an assertion as an unnecessary performance hit. A good practice could be instead to check for matching sizes after initialization of each new task, and each update of a task.

**Comment by neckutrek** [comment]
I have added a checkConsistency method to Task that is called at initialization. This function also prints messages for what went wrong with the task initialization and what is inconsistent to the user. This is pushed to master and devel.
