### ISSUE TITLE
Segfault when removing tasks

### ISSUE THREAD

**Issue by rtkg** [neckutrek/hiqp#15]
Sometimes (though not always) a segfault happens when calling the service to remove all tasks. The function that crashes is TaskManager::getTaskMonitoringData(std::vector<hiqp::TaskMonitoringData, std::allocator<hiqp::TaskMonitoringData> >&).

Can it be that for some reason the controller tries to publish the monitoring data although the task doesn't exist any more ...?

**Comment by neckutrek** [comment]
There are changes made to this on devel that are more recent than what you seem to be running. Could you try the same thing on devel?

**Comment by rtkg** [comment]
Ah, ok - I'll try after merging devel to my hacking branch

**Comment by rtkg** [comment]
Nope, error still happens - also observed in Task::update(RobotStatePtr robot_state) when trying to update the task dynamics:

    dyn_->update(robot_state, def_->e_, def_->J_)

In this case it wasn't a segfault but "terminate called without an active exception". I think there's an update called on a task which was removed already.

**Comment by neckutrek** [comment]
I added mutex locka to all service calls. Latest is on devel.

**Comment by neckutrek** [comment]
Forgot to add it to the update iteration of task manager. Now it's there, see devel.

**Comment by neckutrek** [comment]
I added more mutex locks as I ran in to the problem again. Now also rendering of primitives, and task monitoring is under mutex locks.

**Comment by rtkg** [comment]
The mutex slugfest seems to have solved the problem. Close issue ...?

**Comment by neckutrek** [comment]
Yes close it
