### ISSUE TITLE
Comprehensive list of services

### ISSUE THREAD

**Issue by neckutrek** [neckutrek/hiqp#19]
Could a comprehensive list of services for hiqp be:
- set_task
- remove_task
- remove_all_tasks
- list_all_tasks
- activate_task/deactivate_task
- monitor_task/demonitor_task

- set_primitive
- remove_primitive
- remove_primitives_with_priority  (removes primitives with dependencies to tasks with a certain priority)
- remove_all_primitives
- list_all_primitives

- remove_priority_level
- activate_priority_level/deactivate_priority_level
- monitor_priority_level/demonitor_priority_level
- list_priority_level  (lists tasks and primitives?)

Regarding implementation, all services should be kept in its own class with a pure-virtual interface for implementing the effect of such calls. A ROS/HiQP controller would then inherit from both BaseController and this new HiQPServices class/interface. Or HiQPServices gets a pointer to task manager and sends all service calls to the manager.

**Comment by rtkg** [comment]
Looks good, one question: with (de)activating/(de)monitoring priority levels you mean (de)activating/(de)monitoring  all tasks at a given priority, right?

**Comment by neckutrek** [comment]
The service add_primitive has changed name to set_primitive.

**Comment by neckutrek** [comment]
All have been implemented except for remove_primitives_with_priority (which doesn't make sense as all those primitives have dependencies to tasks), and list_priority_level (which is achievable instead by using list_all_primitives and list_all_tasks).
Latest on devel.
