### ISSUE TITLE
Add yumi_description dependency

### ISSUE THREAD

**Issue by rtkg** [neckutrek/hiqp#3]
The hiqp_ros package should have a runtime dependency on the yumi_description package, since it's used in the yumi_simulation.launch file

**Comment by tstoyanov** [comment]
To avoid pulling in a dependency on the yumi repository I would suggest:
1. move hiqp related demos to the yumi_demos package and put a dependency there
2. add a minimal example robot and example demo into the hiqp stack

**Comment by neckutrek** [comment]
The config, launch files and teleoperation scripts have been moved to github:tstoyanov/yumi_demos/hiqp_yumi_demo.
I kept functional_tests scripts and the old scripts in hiqp_ros for reference. Ideally these should be changed to work with an example robot inside hiqp_ros later.
