### ISSUE TITLE
Uncontrolled joints causing undefined behavior

### ISSUE THREAD

**Issue by rtkg** [neckutrek/hiqp#6]
BaseController::loadJointsAndSetJointHandlesMap() reads the controlled joint names from the controller config files and claims resources (joint handles) for them. However, subsequently all n_j joints from the whole KDL tree are used for Jacobian computations and in task definitions.

BaseController::sampleJointValues() leaves the states uninitialized which currently can cause the optimizer to fail (due to large task dynamic values) and can cause undefined task behaviour since the entries of the task Jacobian corresponding to uncontrolled joints are currently not masked explicitly (see, e.g., TaskJntConfig::init(...)). 

Proposed solution:
   * create separate BaseController::JointHandleMap maps for controlled and uncontrolled joints
   * Wherever Jacobians are computed, explicitly mask the columns corresponding to the uncontrolled joints to zero using the newly created map (also in predefined Jacobians such as in TaskJntConfig)
   * Initialize the states read from the handles in BaseController::sampleJointValues()
 
Side note: BaseController::tip_name_ and BaseController::root_name_ are unused and should be removed.

**Comment by neckutrek** [comment]
The BaseController::JointHandleMap is simply a mapping between KDL's own q_nr identifiers for joints and their names and is used by HiQPJointVelocityController (earlier ROSKinematicsController) to set the correct joint handle when reading joint state data in KDL format.

The RobotStatePtr type is used to send data around the framework that is related to the last sampling state of the robot. It will be extended with a list of joint names, their corresponding q_nr, and whether they are readable and/or writable. It is then up to the author of each task to use that information when forming task definitions and task dynamics. For example, the TDefFullPose task that sets all joints equal to one specific value should then exclude joints that are non-writable.
The read-only joints will be read and the RobotStatePtr data shall be set to 0 and never become undefined.

The BaseController::tip_name_ and BaseController::root_name_ will be removed.

**Comment by neckutrek** [comment]
The jacobian is not masked for other task definitions than TDefFullPose (task_full_pose.cpp). For the other tasks this shouldn't raise any problems, however to avoid code smells the jacobians should be explicitly masked later. For user-defined tasks, the user has to design the jacobians themselves and use the information on writable/non-writable joints from RobotStatePtr.

**Comment by rtkg** [comment]
I think it can be a problem for other tasks as well, if the uncontrolled joint happens to be 'in between' controlled ones - otherwise the KDL Jacobian computation masks automatically.

As a suggestion: isn't the assumption safe that all joints are readable and that it's just a question whether they are controlled (writeable) or not? If so, wouldn't it make sense to replace the two readable/writeable flags in JointHandleInfo with one flag 'controlled' or somesuch?

**Comment by neckutrek** [comment]
You are right, masking needs to be considered for all predefined tasks included in hiqp_core. This still needs fixing.

A joint is essentially a non-static transformation of two reference frames. To it a sensor and/or actuator can be attached. A sensor is "read" from, and an actuator is "written" to. Therefore it makes sense to keep both for consistency with the possible future change into having non-readable-non-writable joints. It would be up to the task author to decide what to do with such joints. Also, a "controllable" joint is a more abstract term while as "readable" and "writable" more concretely tells what actually happens with that joint.
Please tell if you disagree! :)

**Comment by rtkg** [comment]
Nah, the reasoning is fine. The remaining things to do then before closing this issue should be to fix the masking in all predefined tasks.

**Comment by neckutrek** [comment]
I've added jacobian masking to all task definitions now. Closing issue.

**Comment by neckutrek** [comment]
Changes available on devel.
